 languageCode = 'sv-se'
title = 'Mitt Hugo Tema - BlogTree'

[params]
  author = "Christian Karlsson"
  description = "Minimalistisk blogg & länkar"

[[params.socialLinks ]]
  name = "GitHub"
  url = "https://github.com/christiankarlssonxyz"

[[params.socialLinks ]]
    name = "Facebook"
    url = "https://github.com/christiankarlssonxyz"

[[params.socialLinks ]]
    name = "Instagram"
    url = "https://github.com/christiankarlssonxyz"

[[params.socialLinks ]]
      name = "Threads"
      url = "https://github.com/christiankarlssonxyz"
[[params.socialLinks ]]
    name = "X"
    url = "https://github.com/christiankarlssonxyz"

[[params.socialLinks ]]
      name = "Mastodon"
      url = "https://github.com/christiankarlssonxyz"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.157.0'
