baseURL = "https://karlsson.xyz/"
languageCode = 'sv-se'
title = 'Mitt Hugo Tema - BlogTree'

[params]
  author = "John Johnsson"
  description = "Minimalistisk blogg & länkar"

[[params.socialLinks ]]
  name = "GitHub"
  url = "https://github.com"

[[params.socialLinks ]]
    name = "Facebook"
    url = "https://facebook.com"

[[params.socialLinks ]]
    name = "Instagram"
    url = "https://instagram.com"

[[params.socialLinks ]]
      name = "Threads"
      url = "https://github.com/christiankarlssonxyz"
[[params.socialLinks ]]
    name = "X"
    url = "https://x.com"

[[params.socialLinks ]]
      name = "Mastodon"
      url = "https://mastodon.social"

  [[params.socialLinks ]]
            name = "Wordpress"
            url = "https://www.wordpress.com"

[menus]
  [[menus.main]]
    name = 'Startsida'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Artiklar'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Taggar'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.157.0'
